services:
  db:
    image: postgres:latest
    #restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "10000:5432"
    container_name: "spring_dao_jpa"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
